import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error("ERROR: Define NEXT_PUBLIC_SUPABASE_URL y SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const NOMBRES_REGION: Record<string, string> = {
  "AYP": "Region de Arica y Parinacota",
  "TPCA": "Region de Tarapaca",
  "ANTOF": "Region de Antofagasta",
  "ATCMA": "Region de Atacama",
  "COQ": "Region de Coquimbo",
  "VALPO": "Region de Valparaiso",
  "RM": "Region Metropolitana de Santiago",
  "LGBO": "Region del Libertador General Bernardo O'Higgins",
  "MAULE": "Region del Maule",
  "NUBLE": "Region de Nuble",
  "BBIO": "Region del Biobio",
  "ARAUC": "Region de La Araucania",
  "RIOS": "Region de Los Rios",
  "LAGOS": "Region de Los Lagos",
  "AYSEN": "Region de Aysen del General Carlos Ibanez del Campo",
  "MAG": "Region de Magallanes y de la Antartica Chilena",
};

const COMUNAS: { comuna: string; region_cod: string }[] = [
  { comuna: "ARICA", region_cod: "AYP" },
  { comuna: "CAMARONES", region_cod: "AYP" },
  { comuna: "GENERAL LAGOS", region_cod: "AYP" },
  { comuna: "PUTRE", region_cod: "AYP" },
  { comuna: "ALTO HOSPICIO", region_cod: "TPCA" },
  { comuna: "CAMINA", region_cod: "TPCA" },
  { comuna: "COLCHANE", region_cod: "TPCA" },
  { comuna: "HUARA", region_cod: "TPCA" },
  { comuna: "IQUIQUE", region_cod: "TPCA" },
  { comuna: "PICA", region_cod: "TPCA" },
  { comuna: "POZO ALMONTE", region_cod: "TPCA" },
  { comuna: "ANTOFAGASTA", region_cod: "ANTOF" },
  { comuna: "CALAMA", region_cod: "ANTOF" },
  { comuna: "MARIA ELENA", region_cod: "ANTOF" },
  { comuna: "MEJILLONES", region_cod: "ANTOF" },
  { comuna: "OLLAGUE", region_cod: "ANTOF" },
  { comuna: "SAN PEDRO DE ATACAMA", region_cod: "ANTOF" },
  { comuna: "SIERRA GORDA", region_cod: "ANTOF" },
  { comuna: "TALTAL", region_cod: "ANTOF" },
  { comuna: "TOCOPILLA", region_cod: "ANTOF" },
  { comuna: "ALTO DEL CARMEN", region_cod: "ATCMA" },
  { comuna: "CALDERA", region_cod: "ATCMA" },
  { comuna: "CHANARAL", region_cod: "ATCMA" },
  { comuna: "COPIAPO", region_cod: "ATCMA" },
  { comuna: "DIEGO DE ALMAGRO", region_cod: "ATCMA" },
  { comuna: "FREIRINA", region_cod: "ATCMA" },
  { comuna: "HUASCO", region_cod: "ATCMA" },
  { comuna: "TIERRA AMARILLA", region_cod: "ATCMA" },
  { comuna: "VALLENAR", region_cod: "ATCMA" },
  { comuna: "ANDACOLLO", region_cod: "COQ" },
  { comuna: "CANELA", region_cod: "COQ" },
  { comuna: "COMBARBALA", region_cod: "COQ" },
  { comuna: "COQUIMBO", region_cod: "COQ" },
  { comuna: "ILLAPEL", region_cod: "COQ" },
  { comuna: "LA HIGUERA", region_cod: "COQ" },
  { comuna: "LA SERENA", region_cod: "COQ" },
  { comuna: "LOS VILOS", region_cod: "COQ" },
  { comuna: "MONTE PATRIA", region_cod: "COQ" },
  { comuna: "OVALLE", region_cod: "COQ" },
  { comuna: "PAIGUANO", region_cod: "COQ" },
  { comuna: "PUNITAQUI", region_cod: "COQ" },
  { comuna: "RIO HURTADO", region_cod: "COQ" },
  { comuna: "SALAMANCA", region_cod: "COQ" },
  { comuna: "VICUNA", region_cod: "COQ" },
  { comuna: "ALGARROBO", region_cod: "VALPO" },
  { comuna: "CABILDO", region_cod: "VALPO" },
  { comuna: "CALERA", region_cod: "VALPO" },
  { comuna: "CALLE LARGA", region_cod: "VALPO" },
  { comuna: "CARTAGENA", region_cod: "VALPO" },
  { comuna: "CASABLANCA", region_cod: "VALPO" },
  { comuna: "CATEMU", region_cod: "VALPO" },
  { comuna: "CONCON", region_cod: "VALPO" },
  { comuna: "EL QUISCO", region_cod: "VALPO" },
  { comuna: "EL TABO", region_cod: "VALPO" },
  { comuna: "HIJUELAS", region_cod: "VALPO" },
  { comuna: "ISLA DE PASCUA", region_cod: "VALPO" },
  { comuna: "JUAN FERNANDEZ", region_cod: "VALPO" },
  { comuna: "LA CRUZ", region_cod: "VALPO" },
  { comuna: "LA LIGUA", region_cod: "VALPO" },
  { comuna: "LIMACHE", region_cod: "VALPO" },
  { comuna: "LLAILAY", region_cod: "VALPO" },
  { comuna: "LOS ANDES", region_cod: "VALPO" },
  { comuna: "NOGALES", region_cod: "VALPO" },
  { comuna: "OLMUE", region_cod: "VALPO" },
  { comuna: "PANQUEHUE", region_cod: "VALPO" },
  { comuna: "PAPUDO", region_cod: "VALPO" },
  { comuna: "PETORCA", region_cod: "VALPO" },
  { comuna: "PUCHUNCAVI", region_cod: "VALPO" },
  { comuna: "PUTAENDO", region_cod: "VALPO" },
  { comuna: "QUILLOTA", region_cod: "VALPO" },
  { comuna: "QUILPUE", region_cod: "VALPO" },
  { comuna: "QUINTERO", region_cod: "VALPO" },
  { comuna: "RINCONADA", region_cod: "VALPO" },
  { comuna: "SAN ANTONIO", region_cod: "VALPO" },
  { comuna: "SAN ESTEBAN", region_cod: "VALPO" },
  { comuna: "SAN FELIPE", region_cod: "VALPO" },
  { comuna: "SANTA MARIA", region_cod: "VALPO" },
  { comuna: "SANTO DOMINGO", region_cod: "VALPO" },
  { comuna: "VALPARAISO", region_cod: "VALPO" },
  { comuna: "VILLA ALEMANA", region_cod: "VALPO" },
  { comuna: "VINA DEL MAR", region_cod: "VALPO" },
  { comuna: "ZAPALLAR", region_cod: "VALPO" },
  { comuna: "ALHUE", region_cod: "RM" },
  { comuna: "BUIN", region_cod: "RM" },
  { comuna: "CALERA DE TANGO", region_cod: "RM" },
  { comuna: "CERRILLOS", region_cod: "RM" },
  { comuna: "CERRO NAVIA", region_cod: "RM" },
  { comuna: "COLINA", region_cod: "RM" },
  { comuna: "CONCHALI", region_cod: "RM" },
  { comuna: "CURACAVI", region_cod: "RM" },
  { comuna: "EL BOSQUE", region_cod: "RM" },
  { comuna: "EL MONTE", region_cod: "RM" },
  { comuna: "ESTACION CENTRAL", region_cod: "RM" },
  { comuna: "HUECHURABA", region_cod: "RM" },
  { comuna: "INDEPENDENCIA", region_cod: "RM" },
  { comuna: "ISLA DE MAIPO", region_cod: "RM" },
  { comuna: "LA CISTERNA", region_cod: "RM" },
  { comuna: "LA FLORIDA", region_cod: "RM" },
  { comuna: "LA GRANJA", region_cod: "RM" },
  { comuna: "LA PINTANA", region_cod: "RM" },
  { comuna: "LA REINA", region_cod: "RM" },
  { comuna: "LAMPA", region_cod: "RM" },
  { comuna: "LAS CONDES", region_cod: "RM" },
  { comuna: "LO BARNECHEA", region_cod: "RM" },
  { comuna: "LO ESPEJO", region_cod: "RM" },
  { comuna: "LO PRADO", region_cod: "RM" },
  { comuna: "MACUL", region_cod: "RM" },
  { comuna: "MAIPU", region_cod: "RM" },
  { comuna: "MARIA PINTO", region_cod: "RM" },
  { comuna: "MELIPILLA", region_cod: "RM" },
  { comuna: "PADRE HURTADO", region_cod: "RM" },
  { comuna: "PAINE", region_cod: "RM" },
  { comuna: "PEDRO AGUIRRE CERDA", region_cod: "RM" },
  { comuna: "PENAFLOR", region_cod: "RM" },
  { comuna: "PENALOLEN", region_cod: "RM" },
  { comuna: "PIRQUE", region_cod: "RM" },
  { comuna: "PROVIDENCIA", region_cod: "RM" },
  { comuna: "PUDAHUEL", region_cod: "RM" },
  { comuna: "PUENTE ALTO", region_cod: "RM" },
  { comuna: "QUILICURA", region_cod: "RM" },
  { comuna: "QUINTA NORMAL", region_cod: "RM" },
  { comuna: "RECOLETA", region_cod: "RM" },
  { comuna: "RENCA", region_cod: "RM" },
  { comuna: "SAN BERNARDO", region_cod: "RM" },
  { comuna: "SAN JOAQUIN", region_cod: "RM" },
  { comuna: "SAN JOSE DE MAIPO", region_cod: "RM" },
  { comuna: "SAN MIGUEL", region_cod: "RM" },
  { comuna: "SAN PEDRO", region_cod: "RM" },
  { comuna: "SAN RAMON", region_cod: "RM" },
  { comuna: "SANTIAGO", region_cod: "RM" },
  { comuna: "TALAGANTE", region_cod: "RM" },
  { comuna: "TILTIL", region_cod: "RM" },
  { comuna: "VITACURA", region_cod: "RM" },
  { comuna: "NUNOA", region_cod: "RM" },
  { comuna: "CHIMBARONGO", region_cod: "LGBO" },
  { comuna: "CHEPICA", region_cod: "LGBO" },
  { comuna: "CODEGUA", region_cod: "LGBO" },
  { comuna: "COINCO", region_cod: "LGBO" },
  { comuna: "COLTAUCO", region_cod: "LGBO" },
  { comuna: "DONIHUE", region_cod: "LGBO" },
  { comuna: "GRANEROS", region_cod: "LGBO" },
  { comuna: "LA ESTRELLA", region_cod: "LGBO" },
  { comuna: "LAS CABRAS", region_cod: "LGBO" },
  { comuna: "LITUECHE", region_cod: "LGBO" },
  { comuna: "LOLOL", region_cod: "LGBO" },
  { comuna: "MACHALI", region_cod: "LGBO" },
  { comuna: "MALLOA", region_cod: "LGBO" },
  { comuna: "MARCHIHUE", region_cod: "LGBO" },
  { comuna: "MOSTAZAL", region_cod: "LGBO" },
  { comuna: "NANCAGUA", region_cod: "LGBO" },
  { comuna: "NAVIDAD", region_cod: "LGBO" },
  { comuna: "OLIVAR", region_cod: "LGBO" },
  { comuna: "PALMILLA", region_cod: "LGBO" },
  { comuna: "PAREDONES", region_cod: "LGBO" },
  { comuna: "PERALILLO", region_cod: "LGBO" },
  { comuna: "PEUMO", region_cod: "LGBO" },
  { comuna: "PICHIDEGUA", region_cod: "LGBO" },
  { comuna: "PICHILEMU", region_cod: "LGBO" },
  { comuna: "PLACILLA", region_cod: "LGBO" },
  { comuna: "PUMANQUE", region_cod: "LGBO" },
  { comuna: "QUINTA DE TILCOCO", region_cod: "LGBO" },
  { comuna: "RANCAGUA", region_cod: "LGBO" },
  { comuna: "RENGO", region_cod: "LGBO" },
  { comuna: "REQUINOA", region_cod: "LGBO" },
  { comuna: "SAN FERNANDO", region_cod: "LGBO" },
  { comuna: "SAN VICENTE", region_cod: "LGBO" },
  { comuna: "SANTA CRUZ", region_cod: "LGBO" },
  { comuna: "CAUQUENES", region_cod: "MAULE" },
  { comuna: "CHANCO", region_cod: "MAULE" },
  { comuna: "COLBUN", region_cod: "MAULE" },
  { comuna: "CONSTITUCION", region_cod: "MAULE" },
  { comuna: "CUREPTO", region_cod: "MAULE" },
  { comuna: "CURICO", region_cod: "MAULE" },
  { comuna: "EMPEDRADO", region_cod: "MAULE" },
  { comuna: "HUALANE", region_cod: "MAULE" },
  { comuna: "LICANTEN", region_cod: "MAULE" },
  { comuna: "LINARES", region_cod: "MAULE" },
  { comuna: "LONGAVI", region_cod: "MAULE" },
  { comuna: "MAULE", region_cod: "MAULE" },
  { comuna: "MOLINA", region_cod: "MAULE" },
  { comuna: "PARRAL", region_cod: "MAULE" },
  { comuna: "PELARCO", region_cod: "MAULE" },
  { comuna: "PELLUHUE", region_cod: "MAULE" },
  { comuna: "PENCAHUE", region_cod: "MAULE" },
  { comuna: "RAUCO", region_cod: "MAULE" },
  { comuna: "RETIRO", region_cod: "MAULE" },
  { comuna: "ROMERAL", region_cod: "MAULE" },
  { comuna: "RIO CLARO", region_cod: "MAULE" },
  { comuna: "SAGRADA FAMILIA", region_cod: "MAULE" },
  { comuna: "SAN CLEMENTE", region_cod: "MAULE" },
  { comuna: "SAN JAVIER", region_cod: "MAULE" },
  { comuna: "SAN RAFAEL", region_cod: "MAULE" },
  { comuna: "TALCA", region_cod: "MAULE" },
  { comuna: "TENO", region_cod: "MAULE" },
  { comuna: "VICHUQUEN", region_cod: "MAULE" },
  { comuna: "VILLA ALEGRE", region_cod: "MAULE" },
  { comuna: "YERBAS BUENAS", region_cod: "MAULE" },
  { comuna: "BULNES", region_cod: "NUBLE" },
  { comuna: "CHILLAN", region_cod: "NUBLE" },
  { comuna: "CHILLAN VIEJO", region_cod: "NUBLE" },
  { comuna: "COBQUECURA", region_cod: "NUBLE" },
  { comuna: "COELEMU", region_cod: "NUBLE" },
  { comuna: "COIHUECO", region_cod: "NUBLE" },
  { comuna: "EL CARMEN", region_cod: "NUBLE" },
  { comuna: "NINHUE", region_cod: "NUBLE" },
  { comuna: "PEMUCO", region_cod: "NUBLE" },
  { comuna: "PINTO", region_cod: "NUBLE" },
  { comuna: "PORTEZUELO", region_cod: "NUBLE" },
  { comuna: "QUILLON", region_cod: "NUBLE" },
  { comuna: "QUIRIHUE", region_cod: "NUBLE" },
  { comuna: "RANQUIL", region_cod: "NUBLE" },
  { comuna: "SAN CARLOS", region_cod: "NUBLE" },
  { comuna: "SAN FABIAN", region_cod: "NUBLE" },
  { comuna: "SAN IGNACIO", region_cod: "NUBLE" },
  { comuna: "SAN NICOLAS", region_cod: "NUBLE" },
  { comuna: "TREHUACO", region_cod: "NUBLE" },
  { comuna: "YUNGAY", region_cod: "NUBLE" },
  { comuna: "NIQUEN", region_cod: "NUBLE" },
  { comuna: "ALTO BIOBIO", region_cod: "BBIO" },
  { comuna: "ANTUCO", region_cod: "BBIO" },
  { comuna: "ARAuco", region_cod: "BBIO" },
  { comuna: "CABRERO", region_cod: "BBIO" },
  { comuna: "CANETE", region_cod: "BBIO" },
  { comuna: "CHIGUAYANTE", region_cod: "BBIO" },
  { comuna: "CONCEPCION", region_cod: "BBIO" },
  { comuna: "CONTULMO", region_cod: "BBIO" },
  { comuna: "CORONEL", region_cod: "BBIO" },
  { comuna: "CURANILAHUE", region_cod: "BBIO" },
  { comuna: "FLORIDA", region_cod: "BBIO" },
  { comuna: "HUALPEN", region_cod: "BBIO" },
  { comuna: "HUALQUI", region_cod: "BBIO" },
  { comuna: "LAJA", region_cod: "BBIO" },
  { comuna: "LEBU", region_cod: "BBIO" },
  { comuna: "LOS ALAMOS", region_cod: "BBIO" },
  { comuna: "LOS ANGELES", region_cod: "BBIO" },
  { comuna: "LOTA", region_cod: "BBIO" },
  { comuna: "MULCHEN", region_cod: "BBIO" },
  { comuna: "NACIMIENTO", region_cod: "BBIO" },
  { comuna: "NEGRETE", region_cod: "BBIO" },
  { comuna: "PENCO", region_cod: "BBIO" },
  { comuna: "QUILACO", region_cod: "BBIO" },
  { comuna: "QUILLECO", region_cod: "BBIO" },
  { comuna: "SAN PEDRO DE LA PAZ", region_cod: "BBIO" },
  { comuna: "SAN ROSENDO", region_cod: "BBIO" },
  { comuna: "SANTA BARBARA", region_cod: "BBIO" },
  { comuna: "SANTA JUANA", region_cod: "BBIO" },
  { comuna: "TALCAHUANO", region_cod: "BBIO" },
  { comuna: "TIRUA", region_cod: "BBIO" },
  { comuna: "TOME", region_cod: "BBIO" },
  { comuna: "TUCAPEL", region_cod: "BBIO" },
  { comuna: "YUMBEL", region_cod: "BBIO" },
  { comuna: "ANGOL", region_cod: "ARAUC" },
  { comuna: "CARAHUE", region_cod: "ARAUC" },
  { comuna: "CHOLCHOL", region_cod: "ARAUC" },
  { comuna: "COLLIPULLI", region_cod: "ARAUC" },
  { comuna: "CUNCO", region_cod: "ARAUC" },
  { comuna: "CURACAUTIN", region_cod: "ARAUC" },
  { comuna: "CURARREHUE", region_cod: "ARAUC" },
  { comuna: "ERCILLA", region_cod: "ARAUC" },
  { comuna: "FREIRE", region_cod: "ARAUC" },
  { comuna: "GALVARINO", region_cod: "ARAUC" },
  { comuna: "GORBEA", region_cod: "ARAUC" },
  { comuna: "LAUTARO", region_cod: "ARAUC" },
  { comuna: "LONCOCHE", region_cod: "ARAUC" },
  { comuna: "LONQUIMAY", region_cod: "ARAUC" },
  { comuna: "LOS SAUCES", region_cod: "ARAUC" },
  { comuna: "LUMACO", region_cod: "ARAUC" },
  { comuna: "MELIPEUCO", region_cod: "ARAUC" },
  { comuna: "NUEVA IMPERIAL", region_cod: "ARAUC" },
  { comuna: "PADRE LAS CASAS", region_cod: "ARAUC" },
  { comuna: "PERQUENCO", region_cod: "ARAUC" },
  { comuna: "PITRUFQUEN", region_cod: "ARAUC" },
  { comuna: "PUCON", region_cod: "ARAUC" },
  { comuna: "PUREN", region_cod: "ARAUC" },
  { comuna: "RENAICO", region_cod: "ARAUC" },
  { comuna: "SAAVEDRA", region_cod: "ARAUC" },
  { comuna: "TEMUCO", region_cod: "ARAUC" },
  { comuna: "TEODORO SCHMIDT", region_cod: "ARAUC" },
  { comuna: "TOLTEN", region_cod: "ARAUC" },
  { comuna: "TRAIGUEN", region_cod: "ARAUC" },
  { comuna: "VICTORIA", region_cod: "ARAUC" },
  { comuna: "VILCUN", region_cod: "ARAUC" },
  { comuna: "VILLARRICA", region_cod: "ARAUC" },
  { comuna: "CORRAL", region_cod: "RIOS" },
  { comuna: "FUTRONO", region_cod: "RIOS" },
  { comuna: "LA UNION", region_cod: "RIOS" },
  { comuna: "LAGO RANCO", region_cod: "RIOS" },
  { comuna: "LANCO", region_cod: "RIOS" },
  { comuna: "LOS LAGOS", region_cod: "RIOS" },
  { comuna: "MARIQUINA", region_cod: "RIOS" },
  { comuna: "MAFIL", region_cod: "RIOS" },
  { comuna: "PAILLACO", region_cod: "RIOS" },
  { comuna: "PANGUIPULLI", region_cod: "RIOS" },
  { comuna: "RIO BUENO", region_cod: "RIOS" },
  { comuna: "VALDIVIA", region_cod: "RIOS" },
  { comuna: "ANCUD", region_cod: "LAGOS" },
  { comuna: "CALBUCO", region_cod: "LAGOS" },
  { comuna: "CASTRO", region_cod: "LAGOS" },
  { comuna: "CHAITEN", region_cod: "LAGOS" },
  { comuna: "CHONCHI", region_cod: "LAGOS" },
  { comuna: "COCHAMO", region_cod: "LAGOS" },
  { comuna: "CURACO DE VELEZ", region_cod: "LAGOS" },
  { comuna: "DALCAHUE", region_cod: "LAGOS" },
  { comuna: "FRESIA", region_cod: "LAGOS" },
  { comuna: "FRUTILLAR", region_cod: "LAGOS" },
  { comuna: "FUTALEUFU", region_cod: "LAGOS" },
  { comuna: "HUALAIHUE", region_cod: "LAGOS" },
  { comuna: "LLANQUIHUE", region_cod: "LAGOS" },
  { comuna: "LOS MUERMOS", region_cod: "LAGOS" },
  { comuna: "MAULLIN", region_cod: "LAGOS" },
  { comuna: "OSORNO", region_cod: "LAGOS" },
  { comuna: "PALENA", region_cod: "LAGOS" },
  { comuna: "PUERTO MONTT", region_cod: "LAGOS" },
  { comuna: "PUERTO OCTAY", region_cod: "LAGOS" },
  { comuna: "PUERTO VARAS", region_cod: "LAGOS" },
  { comuna: "PUQUELDON", region_cod: "LAGOS" },
  { comuna: "PURRANQUE", region_cod: "LAGOS" },
  { comuna: "PUYEHUE", region_cod: "LAGOS" },
  { comuna: "QUEILEN", region_cod: "LAGOS" },
  { comuna: "QUELLON", region_cod: "LAGOS" },
  { comuna: "QUEMCHI", region_cod: "LAGOS" },
  { comuna: "QUINCHAO", region_cod: "LAGOS" },
  { comuna: "RIO NEGRO", region_cod: "LAGOS" },
  { comuna: "SAN JUAN DE LA COSTA", region_cod: "LAGOS" },
  { comuna: "SAN PABLO", region_cod: "LAGOS" },
  { comuna: "AYSEN", region_cod: "AYSEN" },
  { comuna: "CHILE CHICO", region_cod: "AYSEN" },
  { comuna: "CISNES", region_cod: "AYSEN" },
  { comuna: "COCHRANE", region_cod: "AYSEN" },
  { comuna: "COYHAIQUE", region_cod: "AYSEN" },
  { comuna: "GUAITECAS", region_cod: "AYSEN" },
  { comuna: "LAGO VERDE", region_cod: "AYSEN" },
  { comuna: "O'HIGGINS", region_cod: "AYSEN" },
  { comuna: "RIO IBANEZ", region_cod: "AYSEN" },
  { comuna: "TORTEL", region_cod: "AYSEN" },
  { comuna: "ANTARTICA", region_cod: "MAG" },
  { comuna: "CABO DE HORNOS", region_cod: "MAG" },
  { comuna: "LAGUNA BLANCA", region_cod: "MAG" },
  { comuna: "NATALES", region_cod: "MAG" },
  { comuna: "PORVENIR", region_cod: "MAG" },
  { comuna: "PRIMAVERA", region_cod: "MAG" },
  { comuna: "PUNTA ARENAS", region_cod: "MAG" },
  { comuna: "RIO VERDE", region_cod: "MAG" },
  { comuna: "SAN GREGORIO", region_cod: "MAG" },
  { comuna: "TIMAUKEL", region_cod: "MAG" },
  { comuna: "TORRES DEL PAINE", region_cod: "MAG" },
];

async function main() {
  console.log(`\nImportando ${COMUNAS.length} comunas en ${Object.keys(NOMBRES_REGION).length} regiones...`);

  const data = COMUNAS.map((c) => ({
    comuna: c.comuna,
    region_cod: c.region_cod,
    region_nombre: NOMBRES_REGION[c.region_cod] || c.region_cod,
  }));

  const { error } = await supabaseAdmin.from("comunas").upsert(data, {
    onConflict: "comuna, region_cod",
    ignoreDuplicates: true,
  });

  if (error) {
    console.error("ERROR:", error.message);
  } else {
    console.log(`\n✓ ${COMUNAS.length} comunas importadas en ${Object.keys(NOMBRES_REGION).length} regiones`);
  }
}

main().catch(console.error);
